module Anim.Engine.Scroll.Sub exposing
    ( AnimState, AnimBuilder, AnimMsg
    , AnimEvent(..)
    , init
    , animate
    , update
    , subscriptions
    , delay
    , duration, speed
    , easing
    , stop, stopContainer
    , pause, pauseContainer
    , resume, resumeContainer
    , reset, resetContainer
    , restart, restartContainer
    , anyRunning, isRunning
    , getPosition, getPositionX, getPositionY
    )

{-| Stateful subscription-based scroll animations.

Use this module when you need to track ongoing scrolls, query their state,
react to their progress, or control them mid-flight (pause, resume, stop, etc.).

For detailed guides and examples, see the
[full documentation](https://phollyer.github.io/elm-animate/engines/scroll/).

Use the [Builder](Anim-Engine-Scroll-Builder) module to configure scroll targets.


# Types

@docs AnimState, AnimBuilder, AnimMsg


# Events

@docs AnimEvent


# Initialize

@docs init


# Trigger

@docs animate


# Update

@docs update


# Subscriptions

@docs subscriptions


# Default Settings

@docs delay

@docs duration, speed

@docs easing


# Animation Control


## Stop

@docs stop, stopContainer


## Pause

@docs pause, pauseContainer


## Resume

@docs resume, resumeContainer


## Reset

@docs reset, resetContainer


## Restart

@docs restart, restartContainer


# Querying Animation State

@docs anyRunning, isRunning


# Querying Scroll Position

@docs getPosition, getPositionX, getPositionY

-}

import Anim.Extra.Easing exposing (Easing)
import Anim.Internal.Scroll as InternalScroll


{-| Animation builder type for configuring scroll animations.
-}
type alias AnimBuilder =
    InternalScroll.AnimBuilder


{-| The animation state type used to store scroll animation state.

Store it in your model to track ongoing scrolls, query their state,
react to their progress, or control them mid-flight.

    type alias Model =
        { scrollState : Scroll.AnimState }

-}
type alias AnimState =
    InternalScroll.AnimState


{-| Opaque message type.
-}
type alias AnimMsg =
    InternalScroll.AnimMsg


{-| Animation lifecycle events emitted by the scroll engine.

All events are collected and returned through the [`update`](#update) function,
including events generated by control functions like [`pause`](#pause) or [`stop`](#stop).

  - `Started` - A scroll animation began playing
  - `Ended` - A scroll animation completed naturally
  - `Progress` - A scroll animation frame with current position and progress (0.0 to 1.0)
  - `Stopped` - A scroll animation was stopped via [`stop`](#stop) or [`stopContainer`](#stopContainer)
  - `Paused` - A scroll animation was paused via [`pause`](#pause) or [`pauseContainer`](#pauseContainer)
  - `Resumed` - A scroll animation was resumed via [`resume`](#resume) or [`resumeContainer`](#resumeContainer)
  - `Restarted` - A scroll animation was restarted via [`restart`](#restart) or [`restartContainer`](#restartContainer)

The `String` parameter identifies the container (`"document"` for document body, or the element ID).

-}
type AnimEvent
    = Started String
    | Ended String
    | Progress String { x : Float, y : Float } Float
    | Stopped String
    | Paused String
    | Resumed String
    | Restarted String


{-| Initialize empty scroll animation state.

    init : Model
    init =
        { scrollState = Scroll.init }

-}
init : AnimState
init =
    InternalScroll.init


{-| Trigger a stateful scroll animation.

    type Msg
        = ScrollMsg Scroll.AnimMsg
        | ...

    let
        ( newScrollState, scrollCmd ) =
            Scroll.animate ScrollMsg model.scrollState <|
                scrollToElement "target-section"
    in
    ( { model | scrollState = newScrollState }, scrollCmd )

-}
animate : (AnimMsg -> msg) -> AnimState -> (AnimBuilder -> AnimBuilder) -> ( AnimState, Cmd msg )
animate =
    InternalScroll.animate


{-| Subscribe to receive scroll animation updates.

    type Msg
        = ScrollMsg Scroll.AnimMsg
        | ...

    subscriptions : Model -> Sub Msg
    subscriptions model =
        Scroll.subscriptions ScrollMsg model.scrollState

-}
subscriptions : (AnimMsg -> msg) -> AnimState -> Sub msg
subscriptions =
    InternalScroll.subscriptions


{-| Handle scroll animation lifecycle messages.

    update : Msg -> Model -> ( Model, Cmd Msg )
    update msg model =
        case msg of
            ScrollMsg scrollMsg ->
                let
                    ( newScrollState, events, scrollCmd ) =
                        Scroll.update ScrollMsg scrollMsg model.scrollState
                in
                ( { model | scrollState = newScrollState }, scrollCmd )

-}
update : (AnimMsg -> msg) -> AnimMsg -> AnimState -> ( AnimState, List AnimEvent, Cmd msg )
update toMsg msg animState =
    let
        ( newState, internalEvents, cmd ) =
            InternalScroll.update toMsg msg animState
    in
    ( newState, List.map toAnimEvent internalEvents, cmd )


toAnimEvent : InternalScroll.AnimEvent -> AnimEvent
toAnimEvent event =
    case event of
        InternalScroll.Started cid ->
            Started cid

        InternalScroll.Ended cid ->
            Ended cid

        InternalScroll.Progress cid pos progress ->
            Progress cid pos progress

        InternalScroll.Stopped cid ->
            Stopped cid

        InternalScroll.Paused cid ->
            Paused cid

        InternalScroll.Resumed cid ->
            Resumed cid

        InternalScroll.Restarted cid ->
            Restarted cid



-- GLOBAL SETTINGS


{-| Set the global default duration in milliseconds.

    scrollToElement : String -> AnimBuilder -> AnimBuilder
    scrollToElement elementId =
        Scroll.duration 1000
            >> Builder.forDocument
            >> Builder.toElement elementId
            >> Builder.build

-}
duration : Int -> AnimBuilder -> AnimBuilder
duration =
    InternalScroll.duration


{-| Set the global default speed in pixels per second.

    scrollToElement : String -> AnimBuilder -> AnimBuilder
    scrollToElement elementId =
        Scroll.speed 200
            >> Builder.forDocument
            >> Builder.toElement elementId
            >> Builder.build

-}
speed : Float -> AnimBuilder -> AnimBuilder
speed =
    InternalScroll.speed


{-| Set the global default easing function.

    scrollToElement : String -> AnimBuilder -> AnimBuilder
    scrollToElement elementId =
        Scroll.easing BounceOut
            >> Builder.forDocument
            >> Builder.toElement elementId
            >> Builder.speed 200
            >> Builder.build

-}
easing : Easing -> AnimBuilder -> AnimBuilder
easing =
    InternalScroll.easing


{-| Set the global default delay in milliseconds.

    scrollToElement : String -> AnimBuilder -> AnimBuilder
    scrollToElement elementId =
        Scroll.delay 100
            >> Builder.forDocument
            >> Builder.toElement elementId
            >> Builder.speed 200
            >> Builder.build

-}
delay : Int -> AnimBuilder -> AnimBuilder
delay =
    InternalScroll.delay



-- QUERYING ANIMATION STATE


{-| Check if any scroll animations are currently running.

Returns `Nothing` if there are no animations.

-}
anyRunning : AnimState -> Maybe Bool
anyRunning =
    InternalScroll.anyRunning


{-| Check if a scroll animation for a specific container is currently running.

Use `"document"` for document body.

Returns `Nothing` if there are no animations for the container.

-}
isRunning : String -> AnimState -> Maybe Bool
isRunning =
    InternalScroll.isRunning



-- QUERYING SCROLL POSITION


{-| Get the current scroll position for a specific container.

Returns X and Y coordinates as a record.

Returns `Nothing` if the container is not found or scroll position is unavailable.

-}
getPosition : String -> AnimState -> Maybe { x : Float, y : Float }
getPosition =
    InternalScroll.getScrollPosition


{-| Get current horizontal scroll position for a specific container.
-}
getPositionX : String -> AnimState -> Maybe Float
getPositionX =
    InternalScroll.getScrollPositionX


{-| Get current vertical scroll position for a specific container.
-}
getPositionY : String -> AnimState -> Maybe Float
getPositionY =
    InternalScroll.getScrollPositionY



-- ANIMATION CONTROLS


{-| Stop the document scroll animation by jumping to the target position.

    let
        ( newScrollState, scrollCmd ) =
            Scroll.stop ScrollMsg model.scrollState
    in
    ( { model | scrollState = newScrollState }, scrollCmd )

-}
stop : (AnimMsg -> msg) -> AnimState -> ( AnimState, Cmd msg )
stop toMsg =
    InternalScroll.stopContainer "document" toMsg


{-| Stop a scroll animation for a specific container by jumping to the target position.

    let
        ( newScrollState, scrollCmd ) =
            Scroll.stopContainer "my-container" ScrollMsg model.scrollState
    in
    ( { model | scrollState = newScrollState }, scrollCmd )

-}
stopContainer : String -> (AnimMsg -> msg) -> AnimState -> ( AnimState, Cmd msg )
stopContainer =
    InternalScroll.stopContainer


{-| Pause a document scroll animation.

    Scroll.pause model.scrollState

-}
pause : AnimState -> AnimState
pause =
    InternalScroll.pauseContainer "document"


{-| Pause a scroll animation for a specific container.

    Scroll.pauseContainer "my-container" model.scrollState

-}
pauseContainer : String -> AnimState -> AnimState
pauseContainer =
    InternalScroll.pauseContainer


{-| Resume a document scroll animation.

    Scroll.resume model.scrollState

-}
resume : AnimState -> AnimState
resume =
    InternalScroll.resumeContainer "document"


{-| Resume a scroll animation for a specific container.

    Scroll.resumeContainer "my-container" model.scrollState

-}
resumeContainer : String -> AnimState -> AnimState
resumeContainer =
    InternalScroll.resumeContainer


{-| Reset a document scroll animation to its starting position.

    let
        ( newScrollState, scrollCmd ) =
            Scroll.reset ScrollMsg model.scrollState
    in
    ( { model | scrollState = newScrollState }, scrollCmd )

-}
reset : (AnimMsg -> msg) -> AnimState -> ( AnimState, Cmd msg )
reset toMsg =
    InternalScroll.resetContainer "document" toMsg


{-| Reset a scroll animation for a specific container.

    let
        ( newScrollState, scrollCmd ) =
            Scroll.resetContainer "my-container" ScrollMsg model.scrollState
    in
    ( { model | scrollState = newScrollState }, scrollCmd )

-}
resetContainer : String -> (AnimMsg -> msg) -> AnimState -> ( AnimState, Cmd msg )
resetContainer =
    InternalScroll.resetContainer


{-| Restart a document scroll animation from its starting position.

    let
        ( newScrollState, scrollCmd ) =
            Scroll.restart ScrollMsg model.scrollState
    in
    ( { model | scrollState = newScrollState }, scrollCmd )

-}
restart : (AnimMsg -> msg) -> AnimState -> ( AnimState, Cmd msg )
restart toMsg =
    InternalScroll.restartContainer "document" toMsg


{-| Restart scroll animation for a specific container.

    let
        ( newScrollState, scrollCmd ) =
            Scroll.restartContainer "my-container" ScrollMsg model.scrollState
    in
    ( { model | scrollState = newScrollState }, scrollCmd )

-}
restartContainer : String -> (AnimMsg -> msg) -> AnimState -> ( AnimState, Cmd msg )
restartContainer =
    InternalScroll.restartContainer
